# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tank/cproject/cweb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tank/cproject/cweb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tank/cproject/cweb/CMakeFiles /home/tank/cproject/cweb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tank/cproject/cweb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ACL_HELLO_WORLD

# Build rule for target.
ACL_HELLO_WORLD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ACL_HELLO_WORLD
.PHONY : ACL_HELLO_WORLD

# fast build rule for target.
ACL_HELLO_WORLD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/build
.PHONY : ACL_HELLO_WORLD/fast

controller.o: controller.cpp.o
.PHONY : controller.o

# target to build an object file
controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/controller.cpp.o
.PHONY : controller.cpp.o

controller.i: controller.cpp.i
.PHONY : controller.i

# target to preprocess a source file
controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/controller.cpp.i
.PHONY : controller.cpp.i

controller.s: controller.cpp.s
.PHONY : controller.s

# target to generate assembly for a file
controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/controller.cpp.s
.PHONY : controller.cpp.s

infer.o: infer.cpp.o
.PHONY : infer.o

# target to build an object file
infer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/infer.cpp.o
.PHONY : infer.cpp.o

infer.i: infer.cpp.i
.PHONY : infer.i

# target to preprocess a source file
infer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/infer.cpp.i
.PHONY : infer.cpp.i

infer.s: infer.cpp.s
.PHONY : infer.s

# target to generate assembly for a file
infer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/infer.cpp.s
.PHONY : infer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/main.cpp.s
.PHONY : main.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ACL_HELLO_WORLD.dir/build.make CMakeFiles/ACL_HELLO_WORLD.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ACL_HELLO_WORLD"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... infer.o"
	@echo "... infer.i"
	@echo "... infer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

